title: "nexus. Group AI"
description: "AI-Powered Insights for Better Decisions"
baseurl: ""  # Leave empty for GitHub Pages root
url: "https://orion-f.github.io/nexus-website/"  # Replace with your GitHub Pages URL
