title: "nexus. Group AI"
description: "AI-Powered Insights for Better Decisions"
baseurl: ""  # Leave empty for GitHub Pages root
url: "https://yourusername.github.io/nexus-group-ai"  # Replace with your GitHub Pages URL
